version: '3'
#version: '3.7'
services:
  mongodb:
    image: mongo:3.6.13 #latest
    container_name: mongodb
    hostname: mongodb
    volumes:
      - ./mongodb/mongod.conf:/etc/mongod.conf
      - ./mongodb/initdb.d/:/docker-entrypoint-initdb.d/
      - db-mongo:/home/mongodb/:rw
      - db-home:/home/:rw
      - db-data:/data/db/:rw
      - db-log:/var/log/mongodb/:rw
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: "$MONGO_INITDB_ROOT_USERNAME"
      MONGO_INITDB_ROOT_PASSWORD: "$MONGO_INITDB_ROOT_PASSWORD"
    ports:
      - 27018:27017
    networks:
      - overlay
    command: ["-f", "/etc/mongod.conf"]

  myapp:
    build: .
    container_name: myapp
    hostname: express
    image: node:10.15.3
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    ports:
      - 5001:5000
    networks:
      - overlay
    links:
      - mongodb
    depends_on:
      - mongodb

#
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://myapp:5000/api/ping"]
#      interval: 1m30s
#      timeout: 10s
#      retries: 3
#      # start_period: 40s

#  test: ["CMD-SHELL", "curl -f http://myapp:5000 || exit 1"]



volumes:
  db-data:
  db-log:
  db-home:
  db-mongo:

networks:
  overlay:
